pr:
  - "*"

jobs:
  - job: linux
    pool:
      vmImage: "ubuntu-20.04"
    steps:
      - task: UseDotNet@2
        displayName: .NET Core 3.1 sdk
        inputs:
          version: "3.1.x"
          packageType: sdk

      - task: UseDotNet@2
        displayName: .NET Core 6.0 sdk
        inputs:
          version: "6.0.x"
          packageType: sdk

      - checkout: self
        submodules: true

      - task: Bash@3
        displayName: "Build and Test"
        inputs:
          filePath: "BuildAndTest.sh"
          failOnStderr: true

  - job: windows
    pool:
      vmImage: "windows-latest"
    steps:
      - task: UseDotNet@2
        displayName: .NET Core 3.1 sdk
        inputs:
          version: "3.1.x"
          packageType: sdk

      - task: UseDotNet@2
        displayName: .NET Core 6.0 sdk
        inputs:
          version: "6.0.x"
          packageType: sdk

      - checkout: self
        submodules: true

      - task: CmdLine@2
        displayName: "Build and Test"
        inputs:
          script: "BuildAndTest.cmd"

      - task: ComponentGovernanceComponentDetection@0
        inputs:
          ignoreDirectories: 'src\sarif-sdk'

  - job: mac
    pool:
      vmImage: "macOS-latest"
    steps:
      - task: UseDotNet@2
        displayName: .NET Core 3.1 sdk
        inputs:
          version: "3.1.x"
          packageType: sdk

      - task: UseDotNet@2
        displayName: .NET Core 6.0 sdk
        inputs:
          version: "6.0.x"
          packageType: sdk

      - checkout: self
        submodules: true

      - task: Bash@3
        displayName: "Build and Test"
        inputs:
          filePath: "BuildAndTest.sh"
          failOnStderr: true

      - task: Bash@3
        displayName: "Run BinSkim"
        inputs:
          targetType: "inline"
          script: "dotnet bld/bin/x64_Release/netcoreapp3.1/binskim.dll analyze src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/macho.*"
