pr:
- '*'

jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    submodules: true

  - task: DotNetCoreCLI@2
    name: 'Build'
    inputs:
      command: 'build'
      projects: 'src/*.sln'
      arguments: '--configuration Release'

  # - task: Bash@3
  #   displayName: 'Build and Test'
  #   inputs:
  #     filePath: 'BuildAndTest.sh'

- job: windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
    submodules: true
      
  - task: CmdLine@2
    displayName: 'Build and Test'
    inputs:
      script: 'BuildAndTest.cmd'
