pr:
- '*'

jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    submodules: true

  - task: Bash@3
    displayName: 'Build and Test'
    inputs:
      filePath: 'BuildAndTest.sh'

- job: windows
  pool:
    vmImage: 'windows-latest'
  variables:
    - name: BuildPlatform
      value: 'any cpu'
    - name: BuildConfiguration
      value: 'release'
  steps:
  - checkout: self
    submodules: true

  - task: CmdLine@2
    displayName: 'Build and Test'
    inputs:
      script: 'BuildAndTest.cmd'

  - task: VSTest@2
    displayName: 'Run Reducer UTests'
    inputs:
      testAssemblyVer2: |
        **\$(BuildConfiguration)\netcoreapp3.1\Test.*.dll
        !**\obj\**
      vsTestVersion: latest
      codeCoverageEnabled: true
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'