pr:
- '*'

jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    submodules: true

  - task: Bash@3
    displayName: 'Build and Test'
    inputs:
      filePath: 'BuildAndTest.sh'

- job: windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
    submodules: true

  - task: CmdLine@2
    displayName: 'Build and Test'
    inputs:
      script: 'BuildAndTest.cmd'

  - task: ComponentGovernanceComponentDetection@0
    inputs:
      ignoreDirectories: 'src\sarif-sdk'

- job: mac
  pool:
    vmImage: 'macOS-latest'
  steps:
  - checkout: self
    submodules: true

  - task: Bash@3
    displayName: 'Build and Test'
    inputs:
      filePath: 'BuildAndTest.sh'

  - task: Bash@3
    displayName: 'Run BinSkim'
    inputs:
      targetType: 'inline'
      script: 'dotnet bld/bin/x64_Release/netcoreapp3.1/binskim.dll analyze src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/macho.*'
