pr:
- '*'

jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    submodules: true

  - task: Bash@3
    displayName: 'Build and Test'
    inputs:
      filePath: 'BuildAndTest.sh'

- job: windows
  pool:
    vmImage: 'windows-latest'
  variables:
    - name: BuildPlatform
      value: 'AnyCPU'
    - name: BuildConfiguration
      value: 'Release'
  steps:
  - checkout: self
    submodules: true

  - task: CmdLine@2
    displayName: 'Build and Test'
    inputs:
      script: 'BuildAndTest.cmd'

  - task: ComponentGovernanceComponentDetection@0
