pr:
- '*'

jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    submodules: true

  - task: Bash@3
    displayName: 'Build and Test'
    inputs:
      targetType: 'inline'
      script: |
        dotnet build src/Binskim.sln --configuration Release
        dotnet test src/Binskim.sln --configuration Release --no-build

- job: windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
    submodules: true
      
  - task: CmdLine@2
    displayName: 'Build and Test'
    inputs:
      script: 'BuildAndTest.cmd'
