pr:
- '*'

jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    submodules: true

  - task: DotNetCoreCLI@2
    name: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.sln'
      arguments: '--configuration Release'

  - task: DotNetCoreCLI@2
    name: 'Test'
    inputs:
      command: 'test'
      projects: '**/*.sln'
      arguments: '--configuration Release --no-build'

- job: windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
    submodules: true
      
  - task: CmdLine@2
    displayName: 'Build and Test'
    inputs:
      script: 'BuildAndTest.cmd'
