//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeAnalysis.IL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DriverResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DriverResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodeAnalysis.IL.DriverResources", typeof(DriverResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing {0}....
        /// </summary>
        internal static string Analyzing {
            get {
                return ResourceManager.GetString("Analyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was raised analyzing &apos;{0}&apos; for check &apos;{1}&apos; (which has been disabled for the remainder of the analysis). The exception may have resulted from a problem related to parsing image metadata and not specific to the rule, however. Exception information:
        ///{2}.
        /// </summary>
        internal static string ExceptionAnalyzingTarget {
            get {
                return ResourceManager.GetString("ExceptionAnalyzingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was raised attempting to determine whether &apos;{0}&apos; is a valid analysis target for check &apos;{1}&apos; (which has been disabled for the remainder of the analysis). The exception may have resulted from a problem related to parsing the analysis target and not specific to the rule, however. Exception information:
        ///{2}.
        /// </summary>
        internal static string ExceptionCheckingApplicability {
            get {
                return ResourceManager.GetString("ExceptionCheckingApplicability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was raised attempting to create output file &apos;{0}&apos;. Exception information:
        ///{1}.
        /// </summary>
        internal static string ExceptionCreatingLogFile {
            get {
                return ResourceManager.GetString("ExceptionCreatingLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was raised in the analysis engine..
        /// </summary>
        internal static string ExceptionInAnalysisEngine_Description {
            get {
                return ResourceManager.GetString("ExceptionInAnalysisEngine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was raised initializing check &apos;{0}&apos; (which has been disabled for the remainder of the analysis). Exception information:
        ///{1}.
        /// </summary>
        internal static string ExceptionInitializingRule {
            get {
                return ResourceManager.GetString("ExceptionInitializingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was raised in an analysis rule, indicating an issue with the rule itself or a problem inspecting the binary being analyzed..
        /// </summary>
        internal static string ExceptionInRule_Description {
            get {
                return ResourceManager.GetString("ExceptionInRule_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was raised attempting to load analysis plug-in &apos;{0}&apos;. Exception information:
        ///{1}.
        /// </summary>
        internal static string ExceptionLoadingAnalysisPlugIn {
            get {
                return ResourceManager.GetString("ExceptionLoadingAnalysisPlugIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was raised attempting to load analysis target &apos;{0}&apos;. Exception information:
        ///{1}.
        /// </summary>
        internal static string ExceptionLoadingAnalysisTarget {
            get {
                return ResourceManager.GetString("ExceptionLoadingAnalysisTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was raised while configuring analysis for execution..
        /// </summary>
        internal static string InvalidConfiguration_Description {
            get {
                return ResourceManager.GetString("InvalidConfiguration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A binary was not analyzed as the it does not appear to be a valid portable executable..
        /// </summary>
        internal static string InvalidPE_Description {
            get {
                return ResourceManager.GetString("InvalidPE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No analyzer paths specified.
        /// </summary>
        internal static string NoAnalyzerPathsSpecified {
            get {
                return ResourceManager.GetString("NoAnalyzerPathsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application exited unexpectedly..
        /// </summary>
        internal static string UnexpectedApplicationExit {
            get {
                return ResourceManager.GetString("UnexpectedApplicationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was raised during analysis:
        ///{0}.
        /// </summary>
        internal static string UnhandledEngineException {
            get {
                return ResourceManager.GetString("UnhandledEngineException", resourceCulture);
            }
        }
    }
}
