//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeAnalysis.IL.Rules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodeAnalysis.IL.Rules.RuleResources", typeof(RuleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a 64-bit image with a preferred base address below the 4GB boundary. Having a preferred base address below this boundary triggers a compatibility mode in Address Space Layout Randomization (ASLR) on recent versions of Windows that reduces the number of locations to which ASLR may relocate the binary. This reduces the effectiveness of ASLR at mitigating memory corruption vulnerabilities. To resolve this issue, either use the default preferred base address by removing any uses of /baseaddress from co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2001_Error {
            get {
                return ResourceManager.GetString("BA2001_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64-bit images should have a preferred base address above the 4GB boundary to prevent triggering an Address Space Layout Randomization (ASLR) compatibility mode that decreases security. ASLR compatibility mode reduces the number of locations to which ASLR may relocate the binary, reducing its effectiveness at mitigating memory corruption vulnerabilities. To resolve this issue, either use the default preferred base address by removing any uses of /baseaddress from compiler command lines, or /BASE from linker  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2001_LoadImageAboveFourGigabyteAddress_Description {
            get {
                return ResourceManager.GetString("BA2001_LoadImageAboveFourGigabyteAddress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a 64-bit image with a base address that is &gt;= 4 gigabytes, increasing the effectiveness of Address Space Layout Randomization (which helps prevent attackers from executing security-sensitive code in well-known locations)..
        /// </summary>
        internal static string BA2001_Pass {
            get {
                return ResourceManager.GetString("BA2001_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binaries should not take dependencies on code with known security vulnerabilities..
        /// </summary>
        internal static string BA2002_DoNotIncorporateVulnerableBinaries_Description {
            get {
                return ResourceManager.GetString("BA2002_DoNotIncorporateVulnerableBinaries_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was built with a version of {1} which is subject to the following issues: {2}. To resolve this, {3}. The source files that triggered this were: {4}.
        /// </summary>
        internal static string BA2002_Error {
            get {
                return ResourceManager.GetString("BA2002_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not incorporate any known vulnerable dependencies, as configured by current policy..
        /// </summary>
        internal static string BA2002_Pass {
            get {
                return ResourceManager.GetString("BA2002_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not ship obsolete libraries for which there are known security vulnerabilities..
        /// </summary>
        internal static string BA2005_DoNotShipVulnerableBinaries_Description {
            get {
                return ResourceManager.GetString("BA2005_DoNotShipVulnerableBinaries_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; appears to be an obsolete library (version {1}) for which there are known security vulnerabilities. To resolve this issue, obtain a version of {0} that is newer than version {2}. If this binary is not in fact {0}, ignore this warning..
        /// </summary>
        internal static string BA2005_Error {
            get {
                return ResourceManager.GetString("BA2005_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version information for &apos;{0}&apos; could not be parsed. The binary therefore could not be verified not to be an obsolete binary that is known to be vulnerable to one or more security problems..
        /// </summary>
        internal static string BA2005_Error_CouldNotParseVersion {
            get {
                return ResourceManager.GetString("BA2005_Error_CouldNotParseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vulnerable binary name and version metadata.
        /// </summary>
        internal static string BA2005_MissingRequiredConfiguration {
            get {
                return ResourceManager.GetString("BA2005_MissingRequiredConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not known to be an obsolete binary that is vulnerable to one or more security problems..
        /// </summary>
        internal static string BA2005_Pass {
            get {
                return ResourceManager.GetString("BA2005_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application code should be compiled with the most up-to-date tool sets possible to take advantage of the most current compile-time security features..
        /// </summary>
        internal static string BA2006_BuildWithSecureTools_Description {
            get {
                return ResourceManager.GetString("BA2006_BuildWithSecureTools_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was compiled with one or more modules which were not built using minimum required tool versions (compiler version {1}). More recent toolchains contain mitigations that make it more difficult for an attacker to exploit vulnerabilities in programs they produce. To resolve this issue, compile and/or link your binary with more recent tools. If you are servicing a product where the tool chain cannot be modified (e.g. producing a hotfix for an already shipped version) ignore this warning. Modules built outs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2006_Error {
            get {
                return ResourceManager.GetString("BA2006_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to built with {0} compiler version {1} (Front end version {2}).
        /// </summary>
        internal static string BA2006_Error_BadModule {
            get {
                return ResourceManager.GetString("BA2006_Error_BadModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All linked modules of &apos;{0}&apos; generated by the Microsoft front-end satisfy configured policy (compiler minimum version {1})..
        /// </summary>
        internal static string BA2006_Pass {
            get {
                return ResourceManager.GetString("BA2006_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binaries should be compiled with a warning level that enables all critical security-relevant checks. Enabling at least warning level 3 enables important static analysis in the compiler that can identify bugs with a potential to provoke memory corruption, information disclosure, or double-free vulnerabilities. To resolve this issue, compile at warning level 3 or higher by supplying /W3, /W4, or /Wall to the compiler, and resolve the warnings emitted..
        /// </summary>
        internal static string BA2007_EnableCriticalCompilerWarnings_Description {
            get {
                return ResourceManager.GetString("BA2007_EnableCriticalCompilerWarnings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was compiled at too low a warning level (effective warning level {1} for one or more modules). Warning level 3 enables important static analysis in the compiler to flag bugs that can lead to memory corruption, information disclosure, or double-free vulnerabilities. To resolve this issue, compile at warning level 3 or higher by supplying /W3, /W4, or /Wall to the compiler, and resolve the warnings emitted. An example compiler command line triggering this check: {2}
        ///Modules triggering this check: {3}.
        /// </summary>
        internal static string BA2007_Error_InsufficientWarningLevel {
            get {
                return ResourceManager.GetString("BA2007_Error_InsufficientWarningLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; contains code from an unknown language, preventing a comprehensive analysis of the compiler warning settings. The language could not be identified for the following modules: {1}.
        /// </summary>
        internal static string BA2007_Error_UnknownModuleLanguage {
            get {
                return ResourceManager.GetString("BA2007_Error_UnknownModuleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; disables compiler warning(s) which are required by policy. A compiler warning is typically required if it has a high likelihood of flagging memory corruption, information disclosure, or double-free vulnerabilities. To resolve this issue, enable the indicated warning(s) by removing /Wxxxx switches (where xxxx is a warning id indicated here) from your command line, and resolve any warnings subsequently raised during compilation. An example compiler command line triggering this check was: {1}
        ///Modules tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2007_Error_WarningsDisabled {
            get {
                return ResourceManager.GetString("BA2007_Error_WarningsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was compiled at a secure warning level ({1}) and does not include any modules that disable specific warnings that are required by policy. As a result, it is less likely that memory corruption, information disclosure, double-free and other security-related vulnerabilities exist in code..
        /// </summary>
        internal static string BA2007_Pass {
            get {
                return ResourceManager.GetString("BA2007_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binaries should enable the compiler control guard feature (CFG) at build time to prevent attackers from redirecting execution to unexpected, unsafe locations. CFG analyzes and discovers all indirect-call instructions at compilation and link time. It also injects a check that precedes every indirect call in code that ensures the target is an expected, safe location.  If that check fails at runtime, the operating system will close the program..
        /// </summary>
        internal static string BA2008_EnableControlFlowGuard_Description {
            get {
                return ResourceManager.GetString("BA2008_EnableControlFlowGuard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not enable the control flow guard (CFG) mitigation. To resolve this issue, pass /GUARD:CF on both the compiler and linker command lines. Binaries also require the /DYNAMICBASE linker option in order to enable CFG..
        /// </summary>
        internal static string BA2008_Error {
            get {
                return ResourceManager.GetString("BA2008_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a kernel mode portable executable compiled for a version of Windows that does not support the control flow guard feature for kernel mode binaries..
        /// </summary>
        internal static string BA2008_NotApplicable_UnsupportedKernelModeVersion {
            get {
                return ResourceManager.GetString("BA2008_NotApplicable_UnsupportedKernelModeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; enables the control flow guard mitigation. As a result, the operating system will force an application to close if an attacker is able to redirect execution in the component to an unexpected location..
        /// </summary>
        internal static string BA2008_Pass {
            get {
                return ResourceManager.GetString("BA2008_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binaries should linked as DYNAMICBASE to be eligible for relocation by Address Space Layout Randomization (ASLR). ASLR is an important mitigation that makes it more difficult for an attacker to exploit memory corruption vulnerabilities. Configure your tools to build with this feature enabled. For C and C++ binaries, add /DYNAMICBASE to your linker command line. For .NET applications, use a compiler shipping with Visual Studio 2008 or later..
        /// </summary>
        internal static string BA2009_EnableAddressSpaceLayoutRandomization_Description {
            get {
                return ResourceManager.GetString("BA2009_EnableAddressSpaceLayoutRandomization_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not marked as DYNAMICBASE. This means that the binary is not eligible for relocation by Address Space Layout Randomization (ASLR). ASLR is an important mitigation that makes it more difficult for an attacker to exploit memory corruption vulnerabilities. To resolve this issue, configure your tools to build with this feature enabled. For C and C++ binaries, add /DYNAMICBASE to your linker command line. For .NET applications, use a compiler shipping with Visual Studio 2008 or later..
        /// </summary>
        internal static string BA2009_Error_NotDynamicBase {
            get {
                return ResourceManager.GetString("BA2009_Error_NotDynamicBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is marked as DYNAMICBASE but relocation data has been stripped from the image, preventing address space layout randomization. .
        /// </summary>
        internal static string BA2009_Error_RelocsStripped {
            get {
                return ResourceManager.GetString("BA2009_Error_RelocsStripped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a Windows CE image but does not contain any relocation data, preventing Address Space Layout Randomization..
        /// </summary>
        internal static string BA2009_Error_WinCENoRelocationSection {
            get {
                return ResourceManager.GetString("BA2009_Error_WinCENoRelocationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is properly compiled to enable Address Space Layout Randomization, reducing an attacker&apos;s ability to exploit code in well-known locations..
        /// </summary>
        internal static string BA2009_Pass {
            get {
                return ResourceManager.GetString("BA2009_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE sections should not be marked as both writable and executable. This condition makes it easier for an attacker to exploit memory corruption vulnerabilities, as it may provide an attacker executable location(s) to inject shellcode. Because the loader will always mark the imports section as writable, it is therefore important to mark this section as non-executable. To resolve this issue, ensure that your program does not mark the imports section executable. Look for uses of /SECTION or /MERGE on the linker  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2010_DoNotMarkImportsSectionAsExecutable_Description {
            get {
                return ResourceManager.GetString("BA2010_DoNotMarkImportsSectionAsExecutable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has the imports section marked executable. Because the loader will always mark the imports section as writable, it is important to mark this section as non-executable, so that an attacker cannot place shellcode here. To resolve this issue, ensure that your program does not mark the imports section as executable. Look for uses of /SECTION or /MERGE on the linker command line, or #pragma segment in source code, which change the imports section to be executable, or which merge the &quot;.rdata&quot; segment into a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2010_Error {
            get {
                return ResourceManager.GetString("BA2010_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not have an imports section that is marked as executable, helping to prevent the exploitation of code vulnerabilities..
        /// </summary>
        internal static string BA2010_Pass {
            get {
                return ResourceManager.GetString("BA2010_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binaries should be built with the stack protector buffer security feature (/GS) enabled to increase the difficulty of exploiting stack buffer overflow memory corruption vulnerabilities. To resolve this issue, ensure that all modules compiled into the binary are compiled with the stack protector enabled by supplying /GS on the Visual C++ compiler command line..
        /// </summary>
        internal static string BA2011_EnableStackProtection_Description {
            get {
                return ResourceManager.GetString("BA2011_EnableStackProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a C or C++ binary built with the stack protector buffer security feature disabled in one or more modules. The stack protector (/GS) is a security feature of the compiler which makes it more difficult to exploit stack buffer overflow memory corruption vulnerabilities. To resolve this issue, ensure that your code is compiled with the stack protector enabled by supplying /GS on the Visual C++ compiler command line. The affected modules were: {1}.
        /// </summary>
        internal static string BA2011_Error {
            get {
                return ResourceManager.GetString("BA2011_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; contains code from an unknown language, preventing a comprehensive analysis of the stack protector buffer security features. The language could not be identified for the following modules: {1}..
        /// </summary>
        internal static string BA2011_Error_UnknownModuleLanguage {
            get {
                return ResourceManager.GetString("BA2011_Error_UnknownModuleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a C or C++ binary built with the stack protector buffer security feature enabled for all modules, making it more difficult for an attacker to exploit stack buffer overflow memory corruption vulnerabilities. .
        /// </summary>
        internal static string BA2011_Pass {
            get {
                return ResourceManager.GetString("BA2011_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application code should not interfere with the stack protector. The stack protector (/GS) is a security feature of the compiler which makes it more difficult to exploit stack buffer overflow memory corruption vulnerabilities. The stack protector relies on a random number, called the &quot;security cookie&quot;, to detect these buffer overflows. This &apos;cookie&apos; is statically linked with your binary from a Visual C++ library in the form of the symbol __security_cookie. On recent Windows versions, the loader looks for the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2012_DoNotModifyStackProtectionCookie_Description {
            get {
                return ResourceManager.GetString("BA2012_DoNotModifyStackProtectionCookie_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a C or C++ binary that interferes with the stack protector. The stack protector (/GS) is a security feature of the compiler which makes it more difficult to exploit stack buffer overflow memory corruption vulnerabilities. The stack protector relies on a random number, called the &quot;security cookie&quot;, to detect these buffer overflows. This &apos;cookie&apos; is statically linked with your binary from a Visual C++ library in the form of the symbol __security_cookie. On recent Windows versions, the loader looks fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2012_Error {
            get {
                return ResourceManager.GetString("BA2012_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a C or C++binary that enables the stack protection feature but the security cookie could not be located. The binary may be corrupted..
        /// </summary>
        internal static string BA2012_Error_CouldNotLocateCookie {
            get {
                return ResourceManager.GetString("BA2012_Error_CouldNotLocateCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a C or C++ binary built with the buffer security feature that properly preserves the stack protecter cookie. This has the effect of enabling a significant increase in entropy provided by the operating system over that produced by the C runtime start-up code..
        /// </summary>
        internal static string BA2012_Pass {
            get {
                return ResourceManager.GetString("BA2012_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is  C or C++binary that does not contain a load config table, which indicates either that it was compiled and linked with a version of the compiler that precedes stack protection features or is a binary (such as an ngen&apos;ed assembly) that is not subject to relevant security issues..
        /// </summary>
        internal static string BA2012_Pass_NoLoadConfig {
            get {
                return ResourceManager.GetString("BA2012_Pass_NoLoadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; appears to be a packed C or C++ binary that reports a security cookie offset that exceeds the size of the packed file. Use of the stack protector (/GS) feature therefore could not be verified. The file was possibly packed by: {1}..
        /// </summary>
        internal static string BA2012_Warning_InvalidSecurityCookieOffset {
            get {
                return ResourceManager.GetString("BA2012_Warning_InvalidSecurityCookieOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; appears to be a packed C or C++ binary that reports a security cookie offset that exceeds the size of the packed file. Use of the stack protector (/GS) feature therefore could not be verified. The file was possibly packed by: {1}..
        /// </summary>
        internal static string BA2012_Warning_InvalidSecurityCookieOffsetForPackedImage {
            get {
                return ResourceManager.GetString("BA2012_Warning_InvalidSecurityCookieOffsetForPackedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a C or C++ binary that does not initialize the stack protector. The stack protector (/GS) is a security feature of the compiler which makes it more difficult to exploit stack buffer overflow memory corruption vulnerabilities. The stack protector requires access to entropy in order to be effective, which means a binary must initialize a random number generator at startup, by calling __security_init_cookie() as close to the binary&apos;s entry point as possible. Failing to do so will result in spurious bu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2013_Error {
            get {
                return ResourceManager.GetString("BA2013_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binaries should properly initialize the stack protector (/GS) in order to increase the difficulty of exploiting stack buffer overflow memory corruption vulnerabilities. The stack protector requires access to entropy in order to be effective, which means a binary must initialize a random number generator at startup, by calling __security_init_cookie() as close to the binary&apos;s entry point as possible. Failing to do so will result in spurious buffer overflow detections on the part of the stack protector. To re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2013_InitializeStackProtection_Description {
            get {
                return ResourceManager.GetString("BA2013_InitializeStackProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a C or C++ binary that does not enable the stack protection buffer security feature. It is therefore not required to initialize the stack protector..
        /// </summary>
        internal static string BA2013_NotApplicable_FeatureNotEnabled {
            get {
                return ResourceManager.GetString("BA2013_NotApplicable_FeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a C or C++ binary built with the buffer security feature that properly initializes the stack protecter. This has the effect of increasing the effectiveness of the feature and reducing spurious detections..
        /// </summary>
        internal static string BA2013_Pass {
            get {
                return ResourceManager.GetString("BA2013_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a C or C++ binary that is not required to initialize the stack protection, as it does not contain executable code..
        /// </summary>
        internal static string BA2013_Pass_NoCode {
            get {
                return ResourceManager.GetString("BA2013_Pass_NoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application code should not disable stack protection for individual functions. The stack protector (/GS) is a security feature of the Windows native compiler which makes it more difficult to exploit stack buffer overflow memory corruption vulnerabilities. Disabling the stack protector, even on a function-by-function basis, can compromise the security of code. To resolve this issue, remove occurrences of __declspec(safebuffers) from your code. If the additional code inserted by the stack protector has been s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2014_DoNotDisableStackProtectionForFunctions_Description {
            get {
                return ResourceManager.GetString("BA2014_DoNotDisableStackProtectionForFunctions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a C or C++ binary built with function(s) ({1}) that disable the stack protector. The stack protector (/GS) is a security feature of the compiler which makes it more difficult to exploit stack buffer overflow memory corruption vulnerabilities. Disabling the stack protector, even on a function-by-function basis, is disallowed by SDL policy. To resolve this issue, remove occurrences of __declspec(safebuffers) from your code. If the additional code inserted by the stack protector has been shown in prof [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2014_Error {
            get {
                return ResourceManager.GetString("BA2014_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a C or C++ binary built with the stack protector buffer security feature enabled which does not disable protection for any individual functions (via __declspec(safebuffers), making it more difficult for an attacker to exploit stack buffer overflow memory corruption vulnerabilities..
        /// </summary>
        internal static string BA2014_Pass {
            get {
                return ResourceManager.GetString("BA2014_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binaries should be marked as high entropy Address Space Layout Randomization (ASLR) compatible. High entropy allows ASLR to be more effective in mitigating memory corruption vulnerabilities. To resolve this issue, configure your tool chain to mark the program high entropy compatible; e.g. by supplying /HIGHENTROPYVA to the C or C++ linker command line. Binaries must also be compiled as /LARGEADDRESSAWARE in order to enable high entropy ASLR..
        /// </summary>
        internal static string BA2015_EnableHighEntropyVirtualAddresses_Description {
            get {
                return ResourceManager.GetString("BA2015_EnableHighEntropyVirtualAddresses_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not declare itself as high entropy ASLR compatible. High entropy makes Address Space Layout Randomization more effective in mitigating memory corruption vulnerabilities. To resolve this issue, configure your tools to mark the program high entropy compatible; e.g. by supplying /HIGHENTROPYVA as well as /LARGEADDRESSAWARE to the C or C++ linker command line..
        /// </summary>
        internal static string BA2015_Error_NeitherHighEntropyVANorLargeAddressAware {
            get {
                return ResourceManager.GetString("BA2015_Error_NeitherHighEntropyVANorLargeAddressAware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not declare itself as high entropy ASLR compatible. High entropy makes Address Space Layout Randomization more effective in mitigating memory corruption vulnerabilities. To resolve this issue, configure your tools to mark the program high entropy compatible; e.g. by supplying /HIGHENTROPYVA to the C or C++ linker command line. (This image was determined to have been properly compiled as /LARGEADDRESSAWARE.).
        /// </summary>
        internal static string BA2015_Error_NoHighEntropyVA {
            get {
                return ResourceManager.GetString("BA2015_Error_NoHighEntropyVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not declare itself as high entropy ASLR compatible. High entropy makes Address Space Layout Randomization more effective in mitigating memory corruption vulnerabilities. To resolve this issue, configure your tools to mark the program high entropy compatible by supplying /LARGEADDRESSAWARE to the C or C++ linker command line. (This image was determined to have been properly compiled as /HIGHENTROPYVA.).
        /// </summary>
        internal static string BA2015_Error_NoLargeAddressAware {
            get {
                return ResourceManager.GetString("BA2015_Error_NoLargeAddressAware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is high entropy ASLR compatible, reducing an attacker&apos;s ability to exploit code in well-known locations..
        /// </summary>
        internal static string BA2015_Pass {
            get {
                return ResourceManager.GetString("BA2015_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not marked NX compatible. The NXCompat bit, also known as &quot;Data Execution Prevention&quot; (DEP) or &quot;Execute Disable&quot; (XD), is a processor feature that allows a program to mark a piece of memory as non-executable. This helps mitigate memory corruption vulnerabilities by preventing an attacker from supplying direct shellcode in their exploit, because the exploit comes in the form of input data to the exploited program on a data segment, rather than on an executable code segment. To resolve this issue, en [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2016_Error {
            get {
                return ResourceManager.GetString("BA2016_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binaries should be marked as NX compatible to help prevent execution of untrusted data as code. The NXCompat bit, also known as &quot;Data Execution Prevention&quot; (DEP) or &quot;Execute Disable&quot; (XD), triggers a processor security feature that allows a program to mark a piece of memory as non-executable. This helps mitigate memory corruption vulnerabilities by preventing an attacker from supplying direct shellcode in their exploit (because the exploit comes in the form of input data to the exploited program on a data s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2016_MarkImageAsNXCompatible_Description {
            get {
                return ResourceManager.GetString("BA2016_MarkImageAsNXCompatible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is marked as NX compatible, helping to prevent attackers from executing code that is injected into data segments..
        /// </summary>
        internal static string BA2016_Pass {
            get {
                return ResourceManager.GetString("BA2016_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X86 binaries should enable the SafeSEH mitigation to minimize exploitable memory corruption issues. SafeSEH makes it more difficult to exploit vulnerabilities that permit overwriting SEH control blocks on the stack, by verifying that the location to which a thrown SEH exception would jump is indeed defined as an exception handler in the source program (and not shellcode). To resolve this issue, supply the /SafeSEH flag on the linker command line. Note that you will need to configure your build system to sup [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2018_EnableSafeSEH_Description {
            get {
                return ResourceManager.GetString("BA2018_EnableSafeSEH_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an x86 binary which {1}, indicating that it does not enable the SafeSEH mitigation. SafeSEH makes it more difficult to exploit memory corruption vulnerabilities that can overwrite SEH control blocks on the stack, by verifying that the location to which a thrown SEH exception would jump is indeed defined as an exception handler in the source program (and not shellcode). To resolve this issue, supply the /SafeSEH flag on the linker command line. Note that you will need to configure your build system  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2018_Error {
            get {
                return ResourceManager.GetString("BA2018_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has an empty SE handler table in the load configuration table.
        /// </summary>
        internal static string BA2018_Error_EmptySEHandlerTable {
            get {
                return ResourceManager.GetString("BA2018_Error_EmptySEHandlerTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains an unexpectedly small load configuration table {size 0}.
        /// </summary>
        internal static string BA2018_Error_LoadConfigurationIsTooSmall {
            get {
                return ResourceManager.GetString("BA2018_Error_LoadConfigurationIsTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not contain a load configuration table.
        /// </summary>
        internal static string BA2018_Error_NoLoadConfigurationTable {
            get {
                return ResourceManager.GetString("BA2018_Error_NoLoadConfigurationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has zero SE handlers in the load configuration table.
        /// </summary>
        internal static string BA2018_Error_NoSEHandlers {
            get {
                return ResourceManager.GetString("BA2018_Error_NoSEHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an x86 binary that enables SafeSEH, a mitigation that verifies SEH exception jump targets are defined as exception handlers in the program (and not shellcode)..
        /// </summary>
        internal static string BA2018_Pass {
            get {
                return ResourceManager.GetString("BA2018_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an x86 binary that does not use SEH, making it an invalid target for exploits that attempt to replace SEH jump targets with attacker-controlled shellcode..
        /// </summary>
        internal static string BA2018_Pass_NoSEH {
            get {
                return ResourceManager.GetString("BA2018_Pass_NoSEH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code or data sections should not be marked as both shared and writable. Because these sections are shared across processes, this condition might permit a process with low privilege to alter memory in a higher privilege process. If you do not actually require that a section be both writable and shared, remove one or both of these attributes (by modifying your .DEF file, the appropriate linker /section switch arguments, etc.). If you must share common data across processes (for inter-process communication (IP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2019_DoNotMarkWritableSectionsAsShared_Description {
            get {
                return ResourceManager.GetString("BA2019_DoNotMarkWritableSectionsAsShared_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; contains one or more code or data sections ({1}) which are marked as both shared and writable. Because these sections are shared across processes, this condition might permit a process with low privilege to alter memory in a higher privilege process. If you do not actually require that a section be both writable and shared, remove one or both of these attributes (by modifying your .DEF file, the appropriate linker /section switch arguments, etc.). If you must share common data across processes (for in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2019_Error {
            get {
                return ResourceManager.GetString("BA2019_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; contains no data or code sections marked as both shared and writable, helping to prevent the exploitation of code vulnerabilities..
        /// </summary>
        internal static string BA2019_Pass {
            get {
                return ResourceManager.GetString("BA2019_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE sections should not be marked as both writable and executable. This condition makes it easier for an attacker to exploit memory corruption vulnerabilities, as it may provide an attacker executable location(s) to inject shellcode. To resolve this issue, configure your tools to not emit memory sections that are writable and executable. For example, look for uses of /SECTION on the linker command line for C and C++ programs, or #pragma section in C and C++ source code, which mark a section with both attribu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2021_DoNotMarkWritableSectionsAsExecutable_Description {
            get {
                return ResourceManager.GetString("BA2021_DoNotMarkWritableSectionsAsExecutable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; contains PE section(s) ({1}) that are both writable and executable. Writable and executable memory segments make it easier for an attacker to exploit memory corruption vulnerabilities, because it may provide an attacker executable location(s) to inject shellcode. To resolve this issue, configure your tools to not emit memory sections that are writable and executable. For example, look for uses of /SECTION on the linker command line for C and C++ programs, or #pragma section in C and C++ source code, w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BA2021_Error {
            get {
                return ResourceManager.GetString("BA2021_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has a section alignment ({1}) that is smaller than page size ({2})..
        /// </summary>
        internal static string BA2021_Error_UnexpectedSectionAligment {
            get {
                return ResourceManager.GetString("BA2021_Error_UnexpectedSectionAligment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; contains no data or code sections marked as both shared and executable, helping to prevent the exploitation of code vulnerabilities..
        /// </summary>
        internal static string BA2021_Pass {
            get {
                return ResourceManager.GetString("BA2021_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was signed exclusively with algorithms that WinTrustVerify has flagged as insecure. {1}.
        /// </summary>
        internal static string BA2022_Error_BadSigningAlgorithm {
            get {
                return ResourceManager.GetString("BA2022_Error_BadSigningAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; signing was flagged as insecure by WinTrustVerify with error code &apos;{1}&apos; ({2}).
        /// </summary>
        internal static string BA2022_Error_DidNotVerify {
            get {
                return ResourceManager.GetString("BA2022_Error_DidNotVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; signing could not be completely verified because &apos;{1}&apos; failed with error code: &apos;{2}&apos;..
        /// </summary>
        internal static string BA2022_Error_WinTrustVerifyApiError {
            get {
                return ResourceManager.GetString("BA2022_Error_WinTrustVerifyApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; appears to be signed securely by a trusted publisher with no verification or time stamp errors. Revocation checking was performed on the entire certificate chain, excluding the root certificate. The following digitial signature algorithms were detected: {1}.
        /// </summary>
        internal static string BA2022_Pass {
            get {
                return ResourceManager.GetString("BA2022_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images should be correctly signed by trusted publishers using cryptographically secure signature algorithms. This rule invokes WinTrustVerify to validate that binary hash, signing and public key algorithms are secure and, where configurable, that key sizes meet acceptable size thresholds..
        /// </summary>
        internal static string BA2022_SignCorrectly_Description {
            get {
                return ResourceManager.GetString("BA2022_SignCorrectly_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was not evaluated for check &apos;{1}&apos; as the analysis is not relevant based on observed metadata: {2}..
        /// </summary>
        internal static string NotApplicable_InvalidMetadata {
            get {
                return ResourceManager.GetString("NotApplicable_InvalidMetadata", resourceCulture);
            }
        }
    }
}
