//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeAnalysis.IL.Sdk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SdkResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SdkResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodeAnalysis.IL.Sdk.SdkResources", typeof(SdkResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to cast a binary target to a &apos;{0}&apos; failed.  This indicates a programming error in rules evaluating that sort of target..
        /// </summary>
        internal static string IllegalBinaryCast {
            get {
                return ResourceManager.GetString("IllegalBinaryCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A binary context object was re-initialized with a new file path..
        /// </summary>
        internal static string IllegalContextReuse {
            get {
                return ResourceManager.GetString("IllegalContextReuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an exception occurred attempting to load its pdb.
        /// </summary>
        internal static string MetadataCondition_CouldNotLoadPdb {
            get {
                return ResourceManager.GetString("MetadataCondition_CouldNotLoadPdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELF is not a shared object or executable.
        /// </summary>
        internal static string MetadataCondition_ElfIsCoreNoneOrObject {
            get {
                return ResourceManager.GetString("MetadataCondition_ElfIsCoreNoneOrObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not compiled solely with gcc.
        /// </summary>
        internal static string MetadataCondition_ElfNotBuiltWithGCC {
            get {
                return ResourceManager.GetString("MetadataCondition_ElfNotBuiltWithGCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image was compiled with a toolset version ({0}) that is not sufficiently recent ({1} or newer) to provide relevant settings.
        /// </summary>
        internal static string MetadataCondition_ImageCompiledWithOutdatedTools {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageCompiledWithOutdatedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a 64-bit binary.
        /// </summary>
        internal static string MetadataCondition_ImageIs64BitBinary {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIs64BitBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a boot binary.
        /// </summary>
        internal static string MetadataCondition_ImageIsBootBinary {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsBootBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a .NET core native bootstrap exe.
        /// </summary>
        internal static string MetadataCondition_ImageIsDotNetCoreBootstrapExe {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsDotNetCoreBootstrapExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a .NET core entry point dll.
        /// </summary>
        internal static string MetadataCondition_ImageIsDotNetCoreEntryPointDll {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsDotNetCoreEntryPointDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a binary built by the .NET native toolset.
        /// </summary>
        internal static string MetadataCondition_ImageIsDotNetNativeBinary {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsDotNetNativeBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a .NET native bootstrap exe.
        /// </summary>
        internal static string MetadataCondition_ImageIsDotNetNativeBootstrapExe {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsDotNetNativeBootstrapExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a managed IL library (i.e., ahead of time compiled) assembly.
        /// </summary>
        internal static string MetadataCondition_ImageIsILLibraryAssembly {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsILLibraryAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a managed IL-only assembly.
        /// </summary>
        internal static string MetadataCondition_ImageIsILOnlyAssembly {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsILOnlyAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a managed interop assembly.
        /// </summary>
        internal static string MetadataCondition_ImageIsInteropAssembly {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsInteropAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is not 64-bit (the only architecture that enables control flow guard for kernel mode binaries).
        /// </summary>
        internal static string MetadataCondition_ImageIsKernelModeAndNot64Bit {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsKernelModeAndNot64Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a kernel mode binary.
        /// </summary>
        internal static string MetadataCondition_ImageIsKernelModeBinary {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsKernelModeBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a mixed mode binary.
        /// </summary>
        internal static string MetadataCondition_ImageIsMixedModeBinary {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsMixedModeBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a native UWP (Universal Windows Platform) binary.
        /// </summary>
        internal static string MetadataCondition_ImageIsNativeUniversalWindowsPlatformBinary {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsNativeUniversalWindowsPlatformBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is not a 32-bit binary.
        /// </summary>
        internal static string MetadataCondition_ImageIsNot32BitBinary {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsNot32BitBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is not a 64-bit binary.
        /// </summary>
        internal static string MetadataCondition_ImageIsNot64BitBinary {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsNot64BitBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is not an ELF binary.
        /// </summary>
        internal static string MetadataCondition_ImageIsNotElf {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsNotElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is not an executable program.
        /// </summary>
        internal static string MetadataCondition_ImageIsNotExe {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsNotExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is not a kernel mode binary.
        /// </summary>
        internal static string MetadataCondition_ImageIsNotKernelModeBinary {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsNotKernelModeBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is not a PE binary.
        /// </summary>
        internal static string MetadataCondition_ImageIsNotPE {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsNotPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is not signed .
        /// </summary>
        internal static string MetadataCondition_ImageIsNotSigned {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsNotSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a pre-version 7 Windows CE binary.
        /// </summary>
        internal static string MetadataCondition_ImageIsPreVersion7WindowsCEBinary {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsPreVersion7WindowsCEBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a managed resource-only assembly.
        /// </summary>
        internal static string MetadataCondition_ImageIsResourceOnlyAssembly {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsResourceOnlyAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is a resource-only binary.
        /// </summary>
        internal static string MetadataCondition_ImageIsResourceOnlyBinary {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsResourceOnlyBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image appears to be a WiX bootstrapper application.
        /// </summary>
        internal static string MetadataCondition_ImageIsWixBinary {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsWixBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image is an xbox binary.
        /// </summary>
        internal static string MetadataCondition_ImageIsXboxBinary {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageIsXboxBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image will likely load as a 32-bit process.
        /// </summary>
        internal static string MetadataCondition_ImageLikelyLoads32BitProcess {
            get {
                return ResourceManager.GetString("MetadataCondition_ImageLikelyLoads32BitProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check &apos;{0}&apos; was disabled for this run as the analysis was not configured with required policy ({1}). To resolve this, configure and provide a policy file on the BinSkim command-line using the --policy argument (recommended), or pass --defaultPolicy to invoke built-in settings. Invoke the BinSkim.exe &apos;export&apos; command to produce an initial policy file that can be edited if required and passed back into the tool..
        /// </summary>
        internal static string RuleWasDisabledDueToMissingPolicy {
            get {
                return ResourceManager.GetString("RuleWasDisabledDueToMissingPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was not analyzed as it does not appear to be a valid portable executable..
        /// </summary>
        internal static string TargetNotAnalyzed_NotAPortableExecutable {
            get {
                return ResourceManager.GetString("TargetNotAnalyzed_NotAPortableExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was not evaluated for check &apos;{1}&apos; as the analysis is not relevant based on observed binary metadata: {2}..
        /// </summary>
        internal static string TargetNotAnalyzed_NotApplicable {
            get {
                return ResourceManager.GetString("TargetNotAnalyzed_NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use --level and --kind.
        /// </summary>
        internal static string Verbose_ReplaceWithLevelAndKind {
            get {
                return ResourceManager.GetString("Verbose_ReplaceWithLevelAndKind", resourceCulture);
            }
        }
    }
}
