//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeAnalysis.BinaryParsers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BinaryParsersResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BinaryParsersResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodeAnalysis.BinaryParsers.BinaryParsersResources", typeof(BinaryParsersResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (contact suport).
        /// </summary>
        internal static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dbg file not found.
        /// </summary>
        internal static string DbgNotFound {
            get {
                return ResourceManager.GetString("DbgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive not ready.
        /// </summary>
        internal static string DriveNotReady {
            get {
                return ResourceManager.GetString("DriveNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File system or network error reading Pdb.
        /// </summary>
        internal static string FileNetError {
            get {
                return ResourceManager.GetString("FileNetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid executable image.
        /// </summary>
        internal static string InvalidExecutable {
            get {
                return ResourceManager.GetString("InvalidExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters.
        /// </summary>
        internal static string InvalidParameters {
            get {
                return ResourceManager.GetString("InvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image has invalid timestamp.
        /// </summary>
        internal static string InvalidTimestamp {
            get {
                return ResourceManager.GetString("InvalidTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed debug info or unrecognized format.
        /// </summary>
        internal static string MalformedDebugInfo {
            get {
                return ResourceManager.GetString("MalformedDebugInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched PDB (age).
        /// </summary>
        internal static string MismatchedPdbAge {
            get {
                return ResourceManager.GetString("MismatchedPdbAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched PDB (signature).
        /// </summary>
        internal static string MismatchedPdbSig {
            get {
                return ResourceManager.GetString("MismatchedPdbSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to access a DisposableEnumerable which is non-owning..
        /// </summary>
        internal static string NonOwningDisposableViewAccess {
            get {
                return ResourceManager.GetString("NonOwningDisposableViewAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old pdb version.
        /// </summary>
        internal static string OldPdbVersion {
            get {
                return ResourceManager.GetString("OldPdbVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory.
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdb file is corrupted.
        /// </summary>
        internal static string PdbCorrupted {
            get {
                return ResourceManager.GetString("PdbCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdb has no symbols.
        /// </summary>
        internal static string PdbHasNoSymbols {
            get {
                return ResourceManager.GetString("PdbHasNoSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdb is stripped of cv info.
        /// </summary>
        internal static string PdbStripped {
            get {
                return ResourceManager.GetString("PdbStripped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected hash length for file: .
        /// </summary>
        internal static string UnexpectedHashLength {
            get {
                return ResourceManager.GetString("UnexpectedHashLength", resourceCulture);
            }
        }
    }
}
