name: BuildAndTestBinskim
trigger:
  - "*"

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release 

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: guardian-build-infra-windows-x64-dev
      os: windows
    featureFlags:
      autoEnableRoslynWithNewRuleset: false
    stages:
    - stage: stage1
      displayName: Build And Test
      jobs:
        - job: linux
          pool:
            name: guardian-build-infra-linux-x64-dev
            os: linux
          steps:
          - checkout: self

          - task: UseDotNet@2
            displayName: .NET Core 9 sdk
            inputs:
              version: "9.0.x"
              packageType: sdk

          - task: Bash@3
            displayName: "Build and Test"
            inputs:
              filePath: "BuildAndTest.sh"

        - job: windows
          pool:
            name: guardian-build-infra-windows-x64-dev
            os: windows
          steps:
          - task: UseDotNet@2
            displayName: .NET Core 9 sdk
            inputs:
              version: "9.0.x"
              packageType: sdk

          - checkout: self
          - task: DotNetCoreCLI@2
            inputs:
              command: 'custom'
              custom: 'new'
              arguments: 'nuget.config'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'custom'
              custom: 'nuget'
              arguments: 'add source -n BinSkim.Build https://pkgs.dev.azure.com/mseng/1ES/_packaging/BinSkim.Build/nuget/v3/index.json'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'custom'
              custom: 'nuget'
              arguments: 'disable source nuget'

          - task: CmdLine@2
            displayName: "Build and Test"
            inputs:
              script: "BuildAndTest.cmd"
          - task: ComponentGovernanceComponentDetection@0
