name: dotnet format

on:
  pull_request:
    branches: [ main ]

jobs:
  check-format:
    runs-on: windows-latest

    steps:
    - name: check out code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: dotnet format
      run: dotnet format src --verify-no-changes