name: dotnet format

on:
  pull_request:
    branches: [ main ]

jobs:
  check-format:
    runs-on: windows-latest

    steps:
    - name: check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: dotnet format
      run: dotnet format src --verify-no-changes
